name: Phil Rennie
favicon: null
layout_spectrum: 0.02962
typography_spectrum: 0.39935
title: Phil Rennie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#120d09'
    - '#f2cb90'
    - '#a7561e'
    - '#fefefc'
    - '#557351'
  brandStrength: 0.3527882501948625
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
